name: Code Quality Check

# main 브랜치에 대한 Pull Request가 열릴 때 워크플로 실행
on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint & Prettier Check
    runs-on: ubuntu-latest # GitHub에서 제공하는 최신 Ubuntu 러너에서 실행

    steps:
      # 1. 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3 # PR 코드가 포함된 브랜치를 가져옴

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # 프로젝트에서 사용하는 Node.js 버전에 맞게 설정

      # 3. 의존성 설치 (package-lock.json 기반으로 정확한 버전 설치)
      - name: Install dependencies
        run: npm ci # 'npm install'보다 빠르고 일관성 있게 설치

      # 4. ESLint 검사 실행 (.ts, .tsx 파일 대상)
      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx # 프로젝트 전체에 대해 TypeScript 린트 검사 수행

      # 5. Prettier 포맷 검사
      - name: Run Prettier Check
        run: npx prettier "**/*.{js,ts,jsx,tsx,json,md,css}" --check
        # 지정된 확장자 파일에 대해 포맷이 Prettier 룰에 맞는지 확인 (수정은 하지 않음)
